version: '3.3'

services:
  database:
    image: postgres:15
    container_name: furniture-postgresDB
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
